# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ae_apple/Projects/Minimal-Calculator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ae_apple/Projects/Minimal-Calculator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ae_apple/Projects/Minimal-Calculator/CMakeFiles /home/ae_apple/Projects/Minimal-Calculator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ae_apple/Projects/Minimal-Calculator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AST

# Build rule for target.
AST: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AST
.PHONY : AST

# fast build rule for target.
AST/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AST.dir/build.make CMakeFiles/AST.dir/build
.PHONY : AST/fast

#=============================================================================
# Target rules for targets named Processor

# Build rule for target.
Processor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Processor
.PHONY : Processor

# fast build rule for target.
Processor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Processor.dir/build.make CMakeFiles/Processor.dir/build
.PHONY : Processor/fast

#=============================================================================
# Target rules for targets named App

# Build rule for target.
App: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 App
.PHONY : App

# fast build rule for target.
App/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/App.dir/build.make CMakeFiles/App.dir/build
.PHONY : App/fast

#=============================================================================
# Target rules for targets named calculator

# Build rule for target.
calculator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 calculator
.PHONY : calculator

# fast build rule for target.
calculator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/build
.PHONY : calculator/fast

Calculator/AST/AST.o: Calculator/AST/AST.cpp.o
.PHONY : Calculator/AST/AST.o

# target to build an object file
Calculator/AST/AST.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AST.dir/build.make CMakeFiles/AST.dir/Calculator/AST/AST.cpp.o
.PHONY : Calculator/AST/AST.cpp.o

Calculator/AST/AST.i: Calculator/AST/AST.cpp.i
.PHONY : Calculator/AST/AST.i

# target to preprocess a source file
Calculator/AST/AST.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AST.dir/build.make CMakeFiles/AST.dir/Calculator/AST/AST.cpp.i
.PHONY : Calculator/AST/AST.cpp.i

Calculator/AST/AST.s: Calculator/AST/AST.cpp.s
.PHONY : Calculator/AST/AST.s

# target to generate assembly for a file
Calculator/AST/AST.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AST.dir/build.make CMakeFiles/AST.dir/Calculator/AST/AST.cpp.s
.PHONY : Calculator/AST/AST.cpp.s

Calculator/App.o: Calculator/App.cpp.o
.PHONY : Calculator/App.o

# target to build an object file
Calculator/App.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/App.dir/build.make CMakeFiles/App.dir/Calculator/App.cpp.o
.PHONY : Calculator/App.cpp.o

Calculator/App.i: Calculator/App.cpp.i
.PHONY : Calculator/App.i

# target to preprocess a source file
Calculator/App.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/App.dir/build.make CMakeFiles/App.dir/Calculator/App.cpp.i
.PHONY : Calculator/App.cpp.i

Calculator/App.s: Calculator/App.cpp.s
.PHONY : Calculator/App.s

# target to generate assembly for a file
Calculator/App.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/App.dir/build.make CMakeFiles/App.dir/Calculator/App.cpp.s
.PHONY : Calculator/App.cpp.s

Calculator/Processor/Processor.o: Calculator/Processor/Processor.cpp.o
.PHONY : Calculator/Processor/Processor.o

# target to build an object file
Calculator/Processor/Processor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Processor.dir/build.make CMakeFiles/Processor.dir/Calculator/Processor/Processor.cpp.o
.PHONY : Calculator/Processor/Processor.cpp.o

Calculator/Processor/Processor.i: Calculator/Processor/Processor.cpp.i
.PHONY : Calculator/Processor/Processor.i

# target to preprocess a source file
Calculator/Processor/Processor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Processor.dir/build.make CMakeFiles/Processor.dir/Calculator/Processor/Processor.cpp.i
.PHONY : Calculator/Processor/Processor.cpp.i

Calculator/Processor/Processor.s: Calculator/Processor/Processor.cpp.s
.PHONY : Calculator/Processor/Processor.s

# target to generate assembly for a file
Calculator/Processor/Processor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Processor.dir/build.make CMakeFiles/Processor.dir/Calculator/Processor/Processor.cpp.s
.PHONY : Calculator/Processor/Processor.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AST"
	@echo "... App"
	@echo "... Processor"
	@echo "... calculator"
	@echo "... Calculator/AST/AST.o"
	@echo "... Calculator/AST/AST.i"
	@echo "... Calculator/AST/AST.s"
	@echo "... Calculator/App.o"
	@echo "... Calculator/App.i"
	@echo "... Calculator/App.s"
	@echo "... Calculator/Processor/Processor.o"
	@echo "... Calculator/Processor/Processor.i"
	@echo "... Calculator/Processor/Processor.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

